#!/usr/bin/env python3
"""Emit the on-device AutoFit tables for the pinned EDGE RANGE LAB (C5VRX).

Firmware re-synthesizes the EDGE LUT for the measured VTX deviation and
carrier centre (firmware/edge_autofit.c). Everything that does not depend on
the fit -- PAIR4411 token assignment (kept from the loaded program) and the
eight token observation angles -- comes from this generator; the golden
header lets the host test prove the C synthesis bit-exact against edge_fsm.
Needs the research environment (numpy); outputs are committed.
"""
import json
import sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools/dsp_search'))
LABEL = 'EDGE RANGE LAB'
GOLDEN_FITS = [(1.23, 1.0e6), (0.85, 1.25e6), (1.6, 0.4e6)]


def main():
    import edge_fsm as F
    import generate_range_options as G
    opt = next(o for o in json.loads((ROOT / 'tools/range_options.json').read_text())['options']
               if o['label'] == LABEL)
    p = opt['model']['params']
    assert (p['phases'], p['frequencies'], p['token_bits']) == (4, 32, 3) and p['autofit']
    assert p['detector'] == 'clip' and p['output'] == 'freq' and p['grid'] == 'uniform'
    assert p['leak'] == 0 and p['mix'] == 0 and not p['reliability'] and p['pair_layout'] == '4411'
    _, obs = F.pair_tokens(8, p['observation_vectors'], p['rotation'])
    model = F.synthesize(p)
    assert model['lut'] == opt['model']['lut'], 'pinned LUT is not this synthesis'
    r = lambda v: repr(float(v))
    h = ['#pragma once', '/* Generated by tools/generate_edge_autofit.py (C5VRX by Twotoz/contributors). */',
         f'#define EDGE_AF_MODEL_ID "{G.identity(opt["model"])[:12]}"',
         f'#define EDGE_AF_PINNED_DEVIATION {r(p["fit_deviation"])}',
         f'#define EDGE_AF_PINNED_CENTRE_HZ {r(p["fit_centre_hz"])}',
         f'#define EDGE_AF_KP {r(p["kp"])}', f'#define EDGE_AF_KI {r(p["ki"])}',
         f'#define EDGE_AF_HOLD {r(p["hold"])}', f'#define EDGE_AF_LIMIT {r(p["limit"])}',
         f'#define EDGE_AF_LOW_HZ {r(p["low_hz"])}', f'#define EDGE_AF_HIGH_HZ {r(p["high_hz"])}',
         f'#define EDGE_AF_NOMINAL_HZ {r(F.NOMINAL_CENTRE_HZ)}',
         f'#define EDGE_AF_OFFSET {r(F.B.P.OFFSET)}', f'#define EDGE_AF_SCALE {r(F.B.P.SCALE)}',
         '#ifdef EDGE_AF_TABLE_DATA',
         'static const double edge_af_obs[8] = {' + ', '.join(r(v) for v in obs) + '};', '#endif', '']
    (ROOT / 'firmware/include/edge_autofit_table.h').write_text('\n'.join(h), encoding='utf-8')
    g = ['#pragma once', '/* Generated golden EDGE AutoFit LUTs (edge_fsm.synthesize). */',
         f'#define EDGE_AF_GOLDEN_COUNT {len(GOLDEN_FITS)}',
         'static const double edge_af_golden_fit[][2] = {' +
         ', '.join(f'{{{d!r}, {c!r}}}' for d, c in GOLDEN_FITS) + '};',
         'static const unsigned short edge_af_golden[][1024] = {']
    for d, c in GOLDEN_FITS:
        lut = F.synthesize(dict(p, fit_deviation=d, fit_centre_hz=c))['lut']
        g.append('    {' + ','.join(str(v) for v in lut) + '},')
    g += ['};', '']
    (ROOT / 'tools/edge_autofit_golden.h').write_text('\n'.join(g), encoding='utf-8')
    print('EDGE AutoFit tables for', G.identity(opt['model'])[:12])


if __name__ == '__main__':
    main()
