#!/usr/bin/env python3
"""Generate a focused reverse-engineering report for ESP32-C5 PHY/RF-test blobs.

This script does not modify the vendor libraries. It runs the Espressif RISC-V
binutils against libphy.a/librftest.a and extracts only the functions relevant
to C5VRX's receive-sample research.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import shutil
import subprocess

TARGETS = [
    "adctrig",
    "sampledeal",
    "accumiq",
    "get_iq_est_pwr",
    "dc_iq_est_test",
    "get_rx_buffer",
    "get_rx_data_addr",
    "set_dump_mode",
    "print_dump_data",
    "loop_dump_test",
    "fedump_rd_rxmem",
    "fedump_rd_txmem",
    "phy_chan_dump_cfg_752",
    "phy_adc_rate_set",
    "phy_fe_adc_on",
    "phy_iq_est_enable",
    "phy_iq_est_disable",
    "phy_dc_iq_est",
    "phy_rxiq_get_mis",
    "phy_get_iq_est_snr",
    "phy_fft_scale_force",
    "phy_csidump_force_lltf_cfg",
    "phy_set_rx_pbus_freq",
    "phy_get_rx_pbus_freq",
    "phy_write_chan_freq",
]


def run(cmd: list[str]) -> str:
    p = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
    return p.stdout


def find_tool(name: str) -> str:
    candidates = [f"riscv32-esp-elf-{name}", f"riscv32-unknown-elf-{name}", name]
    for candidate in candidates:
        p = shutil.which(candidate)
        if p:
            return p
    raise SystemExit(f"Could not find {name}. Source/export your ESP-IDF environment first.")


def extract_functions(disassembly: str, symbols: list[str], tail_lines: int = 100) -> dict[str, str]:
    lines = disassembly.splitlines()
    hits: dict[str, str] = {}
    patterns = {s: re.compile(rf"<({re.escape(s)})>:\s*$") for s in symbols}
    for i, line in enumerate(lines):
        for sym, pat in patterns.items():
            if pat.search(line):
                chunk = [line]
                for nxt in lines[i + 1 : i + 1 + tail_lines]:
                    if re.search(r"^[0-9a-fA-F]+\s+<[^>]+>:\s*$", nxt):
                        break
                    chunk.append(nxt)
                hits[sym] = "\n".join(chunk)
    return hits


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--idf", default=os.environ.get("IDF_PATH"), help="ESP-IDF root (defaults to IDF_PATH)")
    ap.add_argument("--out", default="research/generated/phy-analysis.md")
    args = ap.parse_args()

    if not args.idf:
        raise SystemExit("IDF_PATH is not set; pass --idf /path/to/esp-idf")

    root = pathlib.Path(args.idf)
    libdir = root / "components" / "esp_phy" / "lib" / "esp32c5"
    if not libdir.exists() and (root / "esp32c5").exists():
        libdir = root / "esp32c5"

    libs = [libdir / "librftest.a", libdir / "libphy.a"]
    missing = [str(p) for p in libs if not p.exists()]
    if missing:
        raise SystemExit("Missing libraries:\n  " + "\n  ".join(missing))

    nm = find_tool("nm")
    objdump = find_tool("objdump")

    report: list[str] = [
        "# ESP32-C5 PHY blob analysis",
        "",
        "Generated by `tools/analyze_phy.py`.",
        "",
        "The goal is to locate a path from the C5 5 GHz front-end/ADC to raw or near-raw receive samples before normal 802.11 packet decoding.",
        "",
    ]

    for lib in libs:
        report += [f"## `{lib.name}`", ""]
        symbols = run([nm, "-A", "-C", "--defined-only", str(lib)])
        report += ["### Interesting exported symbols", "", "```text"]
        for line in symbols.splitlines():
            if any(t in line for t in TARGETS):
                report.append(line)
        report += ["```", ""]

        dis = run([objdump, "-dr", "-C", str(lib)])
        funcs = extract_functions(dis, TARGETS)
        report += ["### Focused disassembly", ""]
        for target in TARGETS:
            body = funcs.get(target)
            if body:
                report += [f"#### `{target}`", "", "```asm", body, "```", ""]

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(report), encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
