#!/usr/bin/env python3
"""Reproduce C5VRX #150-153 symbol/MMIO evidence from the exact C5 archive."""
import argparse
import hashlib
import re
import subprocess
from pathlib import Path

PIN = "dbf33c418c8d408d4005c849d12a1432deea82e2e5e57de3c8ddf914d104fffb"
SYMBOLS = (
    "phy_chip_set_chan_offset", "phy_disable_agc", "phy_enable_agc",
    "phy_wifi_fbw_sel", "phy_bb_bss_cbw40", "phy_bb_bss_cbw40_dig",
    "phy_bb_cbw_chan_cfg", "phy_rfpll_set_adc_rate", "phy_rx_filter_mode",
    "phy_chan_filt_set", "phy_noise_floor_auto_set", "phy_pkdadc_set",
    "phy_set_cca", "phy_force_txrx_off_new", "phy_open_fe_bb_clk",
    "phy_close_fe_bb_clk", "phy_i2c_readReg", "phy_chip_i2c_readReg",
    "phy_spur_reg_write", "phy_spur_coef_cfg", "phy_rx_table_track", "phy_get_adc_rand",
    "phy_chip_set_chan", "phy_set_chan_misc_new", "phy_set_chan_reg",
    "phy_set_rx_comp_new", "phy_filter_dcap_set", "phy_rc_cal",
    "phy_param_track_tot", "phy_cal_param_track", "phy_rxiq_scale_set",
    "phy_iq_corr_enable", "phy_bb_dcmem_clr",
)

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("archive", type=Path)
    p.add_argument("--objdump", default="riscv32-esp-elf-objdump")
    p.add_argument("--output", type=Path, required=True)
    a = p.parse_args()
    digest = hashlib.sha256(a.archive.read_bytes()).hexdigest()
    if digest != PIN:
        p.error(f"unverified archive SHA256 {digest}; expected {PIN}")
    parts = ["C5VRX by Twotoz and contributors: #150-153 static evidence\n"
             "Espressif esp-phy-lib 59c1234e929212aec0fdda75769b759951235536\n"
             f"ESP32-C5 libphy.a SHA256 {digest}\n"
             "Generated by tools/extract_phy_rx_evidence.py.\n"
             "This is static evidence, not live invocation or sensitivity proof.\n"]
    for symbol in SYMBOLS:
        raw = subprocess.check_output([a.objdump, "-dr", f"--disassemble={symbol}",
                                       str(a.archive)], text=True)
        blocks = re.split(r"(?=Disassembly of section )", raw)
        matches = [b.strip() for b in blocks if f"<{symbol}>:" in b]
        if len(matches) != 1:
            p.error(f"{symbol}: expected one definition, found {len(matches)}")
        parts.append(f"\nSYMBOL {symbol}\n{matches[0]}\n")
    a.output.write_text("\n".join(parts))
    print(f"Verified {len(SYMBOLS)} symbol definitions: {a.output}")

if __name__ == "__main__":
    main()
