#!/usr/bin/env python3
"""Build read-only Phase5-360 oracle tables from the live BSASM sources."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "main/phase5_360_oracle_lut.h"


def words(filename):
    line = next(line for line in (ROOT / "main" / filename).read_text().splitlines()
                if line.startswith("lut "))
    result = [int(word) for word in line.split()[1:]]
    assert len(result) == 1024, (filename, len(result))
    return result


def array(name, values):
    lines = [f"static const uint8_t {name}[{len(values)}] = {{"]
    lines.extend("    " + ", ".join(f"{value:2d}" for value in values[i:i + 16]) + ","
                 for i in range(0, len(values), 16))
    lines.append("};")
    return "\n".join(lines)


def main():
    golden = words("fm.bsasm")
    live = words("fm_phase5_360.bsasm")
    phases = [(golden[raw] >> 8) & 31 for raw in range(256)]
    assert all((live[raw] & 31) == phases[raw] for raw in range(256))
    data = [
        "/* Generated by tools/gen_phase5_360_oracle_lut.py; do not edit.\n"
        " * Read-only slow-path tables. These do not change the live BitScrambler. */",
        "#pragma once\n#include <stdint.h>",
        array("s_phase5_360_raw_phase", phases),
        array("s_phase5_360_golden_dac", [word & 63 for word in golden]),
        array("s_phase5_360_live_dac", [(word >> 8) & 63 for word in live]),
        "",
    ]
    OUT.write_text("\n\n".join(data), encoding="utf-8")
    print(f"Generated {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
